version: 2
updates:
  # Python dependencies via uv/pyproject.toml
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "andrewm4894"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "django"
        update-types: ["version-update:semver-major"]
      - dependency-name: "djangorestframework"
        update-types: ["version-update:semver-major"]

  # Frontend dependencies (React/Node.js)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "javascript"
    reviewers:
      - "andrewm4894"
    ignore:
      # Ignore major React updates (need manual testing)
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-scripts"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "andrewm4894"