repos:
  # Python hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^(\.venv/|frontend/|example-apps/|migrations/)

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^(\.venv/|frontend/|example-apps/|migrations/)

  # Python linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: ^(\.venv/|frontend/|example-apps/|migrations/)

  # JavaScript/React formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|css|md|json)$
        exclude: ^(venv/|node_modules/|build/|dist/)

  # JavaScript/React linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        files: \.(js|jsx)$
        exclude: ^(venv/|node_modules/|build/|dist/|example-apps/)
        additional_dependencies:
          - eslint@^8.0.0
          - eslint-config-react-app

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        exclude: ^(venv/|frontend/|example-apps/|tests?/)
        args: [-ll]

  # Django specific checks
  - repo: local
    hooks:
      - id: django-check
        name: Django Check
        entry: uv run python manage.py check
        language: system
        pass_filenames: false
        files: \.(py)$
        exclude: ^(\.venv/|frontend/|example-apps/)