# Generated by Django 5.2.6 on 2025-09-07 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address')),
                ('minute_bucket', models.DateTimeField(help_text='Minute bucket (rounded down)')),
                ('request_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'minute_bucket'], name='analytics_i_ip_addr_419642_idx'), models.Index(fields=['minute_bucket'], name='analytics_i_minute__b528ae_idx')],
                'unique_together': {('ip_address', 'minute_bucket')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable project name', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('api_key', models.CharField(help_text='Public API key', max_length=64, unique=True)),
                ('secret_key', models.CharField(help_text='Secret key (optional, for server-side)', max_length=64, unique=True)),
                ('allowed_sources', models.JSONField(blank=True, default=list, help_text='List of allowed source names (empty = allow all)')),
                ('rate_limit_per_minute', models.IntegerField(default=1000, help_text='Maximum events per minute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['api_key'], name='analytics_p_api_key_99ed90_idx'), models.Index(fields=['is_active'], name='analytics_p_is_acti_83a9cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('source', models.CharField(default='web', help_text='Source application or system', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('user_id', models.CharField(blank=True, help_text='User identifier (anonymous cookie-based or authenticated)', max_length=64, null=True)),
                ('session_id', models.CharField(blank=True, help_text='Session identifier (auto-generated: user_id_date_random)', max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('project', models.ForeignKey(help_text='Project that sent this event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.project')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', 'source', 'event_name'], name='analytics_e_project_13dd32_idx'), models.Index(fields=['project', 'timestamp'], name='analytics_e_project_aeee3d_idx'), models.Index(fields=['timestamp'], name='analytics_e_timesta_fdc538_idx'), models.Index(fields=['user_id'], name='analytics_e_user_id_cd8466_idx'), models.Index(fields=['session_id'], name='analytics_e_session_83836a_idx'), models.Index(fields=['project', 'user_id'], name='analytics_e_project_a91a2a_idx'), models.Index(fields=['project', 'session_id'], name='analytics_e_project_fe6475_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute_bucket', models.DateTimeField(help_text='Minute bucket (rounded down)')),
                ('request_count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'minute_bucket'], name='analytics_p_project_8e672c_idx')],
                'unique_together': {('project', 'minute_bucket')},
            },
        ),
    ]
