# Generated by Django 5.2.6 on 2025-09-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_default",
            field=models.BooleanField(default=False, help_text="Default project for dashboard"),
        ),
    ]
