# Generated by Django 5.2.6 on 2025-09-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(default='web', help_text='Source application or system', max_length=50),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['source', 'event_name'], name='analytics_e_source_e22f42_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp'], name='analytics_e_timesta_fdc538_idx'),
        ),
    ]
